name: eShopOnWeb Build and Test

#Triggers (uncomment line below to use it)
#on: [push, workflow_dispatch]

on:
  push:
    branches:
      - main
  workflow_dispatch:

#Environment variables https://docs.github.com/en/actions/learn-github-actions/environment-variables
env:
  RESOURCE-GROUP: rg-eshoponweb
  LOCATION: westus2
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: a3a49cf0-afce-4ad3-8dcd-34be88f2cb93
  WEBAPP-NAME: eshoponweb-webapp55229130


jobs:
  #Build, test and publish .net web project in repository
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    #checkout the repository
    - uses: actions/checkout@v4
    #prepare runner for desired .net version SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Restore dependencies
      run: dotnet restore ./eShopOnWeb.sln
    #Build/Test/Publish the .net project
    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
   
    - name: dotnet publish
      run: |
        dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
        cd ${{env.DOTNET_ROOT}}/myapp
        zip -r ../app.zip .
    # upload the published website code artifacts
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/app.zip
        
    # upload the bicep template as artifacts for next job
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v4
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE-FILE }}
        
  # Use Bicep to deploy infrastructure + Publish webapp 
  deploy:
  runs-on: ubuntu-latest
  needs: buildandtest
  environment:
    name: 'Development'
  steps:
    - name: Download .NET app artifact
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: .net-app

    - name: Download Bicep template
      uses: actions/download-artifact@v4
      with:
        name: bicep-template
        path: bicep-template

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Pre-deployment: Check SP permissions
    - name: Check Service Principal Permissions
      uses: Azure/cli@v2
      with:
        inlineScript: |
          ROLE_COUNT=$(az role assignment list \
            --assignee $(az account show --query user.name -o tsv) \
            --scope /subscriptions/${{ env.SUBSCRIPTION-ID }}/resourceGroups/${{ env.RESOURCE-GROUP }} \
            --query "length(@)")
          echo "Role assignments count: $ROLE_COUNT"
          if [ "$ROLE_COUNT" -eq 0 ]; then
            echo "ERROR: Service Principal has no roles on the resource group. Aborting deployment."
            exit 1
          fi

    # Upgrade Azure CLI to latest version
    - name: Upgrade Azure CLI
      run: az upgrade --yes

    # Validate Bicep template
    - name: Validate Bicep template
      uses: Azure/cli@v2
      with:
        inlineScript: |
          az deployment group validate \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --template-file bicep-template/webapp.bicep \
            --parameters webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}

    # Deploy Bicep template
    - name: Deploy Bicep Template
      uses: Azure/cli@v2
      with:
        inlineScript: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --template-file bicep-template/webapp.bicep \
            --parameters webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}

    # Deploy website via ZIP
    - name: Publish Website to WebApp
      uses: Azure/cli@v2
      with:
        inlineScript: |
          az webapp deploy \
            --name ${{ env.WEBAPP-NAME }} \
            --resource-group ${{ env.RESOURCE-GROUP }} \
            --src-path .net-app/app.zip \
            --type zip
